const AGENDA_URL='';(()=>{'use strict';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');menu.onclick=()=>{const o=nav.classList.toggle('open');menu.setAttribute('aria-expanded',o)};document.querySelectorAll('.navlinks a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const header=document.querySelector('.header');let last=scrollY;addEventListener('scroll',()=>{const y=scrollY;header.classList.toggle('hide',y>last&&y>180);last=y},{passive:true});
if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('shown');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('[data-reveal]').forEach(e=>io.observe(e))}else document.querySelectorAll('[data-reveal]').forEach(e=>e.classList.add('shown'));
if(reduced)document.querySelectorAll('[data-count]').forEach(e=>e.textContent=e.dataset.decimal?'5,0':e.dataset.count);else{const co=new IntersectionObserver(es=>es.forEach(x=>{if(!x.isIntersecting)return;document.querySelectorAll('[data-count]').forEach(e=>{const end=+e.dataset.count,s=performance.now();function f(n){const p=Math.min(1,(n-s)/900),v=end*(1-Math.pow(1-p,3));e.textContent=e.dataset.decimal?v.toFixed(1).replace('.',','):Math.round(v);if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)});co.disconnect()}));co.observe(document.querySelector('.proof'))}
document.addEventListener('focusin',e=>{if(e.target.matches('input,textarea'))document.body.classList.add('keyboard')});document.addEventListener('focusout',()=>setTimeout(()=>document.body.classList.remove('keyboard'),120));if(reduced){const v=document.querySelector('.herovideo');v.pause();v.removeAttribute('autoplay')}
let mode='online';document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});document.getElementById('focusbook').onclick=()=>document.getElementById('bookname').focus();document.getElementById('bookform').onsubmit=e=>{e.preventDefault();const f=document.getElementById('agendaframe'),i=document.getElementById('agendaiframe'),fb=document.getElementById('fallback');f.classList.add('show');if(AGENDA_URL){i.src=AGENDA_URL;i.hidden=false;fb.hidden=true}else{i.hidden=true;fb.hidden=false}document.getElementById('confirm').classList.add('show');f.scrollIntoView({behavior:reduced?'auto':'smooth'})};
document.querySelectorAll('.play').forEach(b=>b.onclick=async()=>{const s=b.closest('.stage'),v=s.querySelector('video'),err=b.closest('.videocard').querySelector('.videoerror');document.querySelectorAll('.stage video').forEach(x=>{if(x!==v){x.pause();x.closest('.stage').classList.remove('playing')}});if(!v.src)v.src=v.dataset.src;s.classList.add('playing');v.controls=true;try{await v.play();err.textContent=''}catch{err.textContent='Não foi possível reproduzir.'}});
document.querySelectorAll('.faqq').forEach(q=>q.onclick=()=>{const o=q.getAttribute('aria-expanded')==='true';document.querySelectorAll('.faqq').forEach(x=>x.setAttribute('aria-expanded','false'));q.setAttribute('aria-expanded',!o)});const d=document.getElementById('dialog');document.querySelectorAll('.areacard').forEach(c=>c.onclick=()=>{document.getElementById('dialogtitle').textContent=c.dataset.title;document.getElementById('dialogtext').textContent=c.dataset.text;d.showModal()});d.querySelector('.close').onclick=()=>d.close();
document.getElementById('guideform').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);document.getElementById('guidesuccess').classList.add('show');window.open('https://wa.me/5547996529582?text='+encodeURIComponent(`Olá, meu nome é ${fd.get('nome')}. Gostaria de receber o guia. Meu WhatsApp é ${fd.get('whatsapp')}.`),'_blank','noopener')};
document.querySelectorAll('[data-carousel]').forEach(r=>{const dots=document.querySelectorAll(`[data-dots="${r.dataset.carousel}"] .dot`);r.addEventListener('scroll',()=>requestAnimationFrame(()=>{const c=[...r.children],mid=r.scrollLeft+r.clientWidth/2;let a=0,b=Infinity;c.forEach((x,j)=>{const z=Math.abs(x.offsetLeft+x.offsetWidth/2-mid);if(z<b){b=z;a=j}});dots.forEach((x,j)=>x.classList.toggle('active',j===a))}),{passive:true});dots.forEach((x,j)=>x.onclick=()=>r.children[j]?.scrollIntoView({behavior:reduced?'auto':'smooth',inline:'center'}))});
})();